version: "3.1"

services:
  grafana:
    restart: always
    container_name: grafana
    image: "grafana/grafana:9.2.15"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
  loki:
    restart: always
    container_name: loki
    image: "grafana/loki:2.8.0"
    ports:
      - "3100:3100"
    depends_on:
    - grafana
  web_admin:
    restart: always
    container_name: web_admin
    build: .
    command: >
      bash -c "python manage.py migrate && uvicorn main.asgi:application --host 0.0.0.0"
    volumes:
      - .:/main
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    logging: #  docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    depends_on:
    - loki
  tgbot:
    container_name: bot
    build: .
    command: python3 manage.py run_bot
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    volumes:
      - .:/main
    depends_on:
    - web_admin
    - redis
    - loki
    logging:  #  docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
  celery:
    restart: always
    container_name: celery
    volumes:
      - .:/main
    build: .
    env_file:
      - ".env"
    command: >
      bash -c "celery -A main worker -l info"
    depends_on:
      - redis
  flower:
    restart: always
    container_name: flower
    volumes:
      - .:/main
    build: .
    ports:
      - "5555:5555"
    command: >
       bash -c "celery -A main flower --port=5555"
    depends_on:
    - celery


networks:
  botnet:
    driver: bridge

