version: "3.1"

services:
  web_admin:
    container_name: web_admin
    build: .
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/main
    ports:
      - "8000:8000"
    env_file:
      - ".env"
  tgbot:
    container_name: bot
    build:
      context: .
    command: python3 manage.py run_bot
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    volumes:
      - .:/main
    depends_on:
    - web_admin
    - redis
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
  celery:
    container_name: celery
    build:
      context: .
    env_file:
      - ".env"
    command: >
      bash -c "celery -A main worker -l info"
    depends_on:
      - redis
  flower:
    container_name: flower
    build:
      context: .
    ports:
      - "5555:5555"
    command: >
       bash -c "celery -A main flower --port=5555"
    depends_on:
    - celery

networks:
  botnet:
    driver: bridge

