# Generated by Django 4.2.7 on 2024-04-09 22:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateLessonFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(verbose_name='Дата начала:')),
                ('create_to', models.DateField(verbose_name='Дата окончания:')),
                ('schedule', models.FileField(upload_to='bot/', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Недельное расписание группового занятия',
                'verbose_name_plural': 'Недельные расписания групповых занятий',
            },
        ),
        migrations.CreateModel(
            name='LessonFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Групповое занятие',
                'verbose_name_plural': 'Групповые занятия',
            },
        ),
        migrations.CreateModel(
            name='TrainerFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Тренер тренажерного зала',
                'verbose_name_plural': 'Тренеры тренажерного зала',
            },
        ),
        migrations.CreateModel(
            name='UserFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Номер карты')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Телефонный номер должен быть в формате +7-999-999-99-99', regex='^\\+7-\\d{3}-\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('relative_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.userfit', verbose_name='Родственник')),
            ],
            options={
                'verbose_name': 'Клиент тренажерного зала',
                'verbose_name_plural': 'Клиенты тренажерного зала',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='ID пользователя telegram')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='Авторизация')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='Никнейм')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
                ('card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.userfit', verbose_name='Номер карты')),
            ],
            options={
                'verbose_name': 'Пользователь тлеграмма',
                'verbose_name_plural': 'Пользователи телеграмма',
            },
        ),
    ]
