# Generated by Django 4.2.7 on 2024-03-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField(unique=True, verbose_name='Номер карты')),
                ('telegram_user_id', models.IntegerField(unique=True, verbose_name='ID пользователя telegram')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь тлеграмма',
            },
        ),
    ]
