# Generated by Django 4.2.7 on 2024-03-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFitLesson',
        ),
    ]
