# Generated by Django 4.2.7 on 2024-03-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfit',
            name='date_time',
            field=models.ManyToManyField(blank=True, related_name='lessonfit_datelessonfit', to='bot.datelessonfit', verbose_name='Промежуточное расписание'),
        ),
        migrations.AlterField(
            model_name='lessonfit',
            name='time',
            field=models.ManyToManyField(blank=True, related_name='lessonfit_timelessonfit', to='bot.timelessonfit', verbose_name='Дата и время занятия'),
        ),
        migrations.AlterField(
            model_name='timelessonfit',
            name='time',
            field=models.DateTimeField(verbose_name='Время занятия'),
        ),
    ]
