# Generated by Django 4.2.7 on 2024-04-15 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Пользователь телеграмма', 'verbose_name_plural': 'Пользователи телеграмма'},
        ),
        migrations.AlterField(
            model_name='datelessonfit',
            name='schedule',
            field=models.FileField(upload_to='bot/', validators=[django.core.validators.RegexValidator(message='Файл название файла должно содержать интервал меся и день, например: 01.13-01.20', regex='^\\d{2}.\\d{2}-\\d{2}.\\d{2}$')], verbose_name='Расписание'),
        ),
    ]
