# Generated by Django 4.2.7 on 2024-03-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfit',
            name='phone',
            field=models.IntegerField(max_length=20, verbose_name='Телефон'),
        ),
    ]
