# Generated by Django 4.2.7 on 2024-03-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerfit',
            name='lesson',
        ),
        migrations.AddField(
            model_name='trainerfit',
            name='lesson',
            field=models.ManyToManyField(blank=True, related_name='trainer_lesson', to='bot.lessonfit', verbose_name='Занятия'),
        ),
    ]
