# Generated by Django 4.2.7 on 2024-03-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_datelessonfit_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datelessonfit',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='trainerfit',
            name='dae_lesson',
        ),
        migrations.AddField(
            model_name='lessonfit',
            name='date_time',
            field=models.ManyToManyField(blank=True, related_name='lessonfit_datelessonfit', to='bot.datelessonfit', verbose_name='Промежуточное расписание'),
        ),
        migrations.AddField(
            model_name='trainerfit',
            name='lesson',
            field=models.ManyToManyField(blank=True, related_name='trainerfit_lessonfit', to='bot.lessonfit', verbose_name='Занятия'),
        ),
        migrations.AlterField(
            model_name='datelessonfit',
            name='schedule',
            field=models.FileField(upload_to='bot/', verbose_name='Расписание'),
        ),
    ]
