# Generated by Django 4.2.7 on 2024-03-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_trainerfit_lesson_trainerfit_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonfit',
            name='time',
        ),
        migrations.AddField(
            model_name='lessonfit',
            name='time',
            field=models.ManyToManyField(blank=True, related_name='lesson_time', to='bot.timelessonfit', verbose_name='Дата и время занятия'),
        ),
    ]
