# Generated by Django 4.2.7 on 2024-03-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_userfit_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfit',
            name='phone',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
    ]
