# Generated by Django 4.2.7 on 2024-03-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_telegramuser_card_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Пользователь тлеграмма', 'verbose_name_plural': 'Пользователи телеграмма'},
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_authenticated',
            field=models.BooleanField(default=False, verbose_name='Авторизация'),
        ),
    ]
