# Generated by Django 4.2.7 on 2024-03-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_delete_timelessonfit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfit',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
    ]
