# Generated by Django 4.2.7 on 2024-03-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_userfit_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfit',
            name='relative_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.userfit', verbose_name='Родственник'),
        ),
    ]
