# Generated by Django 4.2.7 on 2024-03-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_userfitlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonfit',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='timelessonfit',
            name='time',
            field=models.DateTimeField(db_index=True, verbose_name='Время занятия'),
        ),
        migrations.AlterField(
            model_name='userfit',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userfit',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Фамилия'),
        ),
    ]
