# Generated by Django 4.2.7 on 2024-04-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_datelessonfit_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datelessonfit',
            name='schedule',
            field=models.ImageField(upload_to='bot/lesson_schedule/', verbose_name='Расписание'),
        ),
    ]
