# Generated by Django 4.2.7 on 2024-03-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_telegramuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Номер карты')),
                ('fisrt_name', models.CharField(verbose_name='Имя клиента')),
                ('last_name', models.CharField(verbose_name='Фамилия клиента')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало абонемента')),
                ('created_to', models.DateTimeField(blank=True, null=True, verbose_name='Конец абонемента')),
                ('actived', models.BooleanField(default=False, verbose_name='Активен абонемент')),
                ('phone', models.PositiveIntegerField(max_length=11, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиент тренажерного зала',
                'verbose_name_plural': 'Клиенты тренажерного зала',
            },
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='card_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.userfit', verbose_name='Номер карты'),
        ),
    ]
