# Generated by Django 4.2.7 on 2024-04-15 11:27

import bot.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_datelessonfit_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datelessonfit',
            name='schedule',
            field=bot.models.ImageOrDocumentField(upload_to='bot/lesson_schedule/', verbose_name='Расписание'),
        ),
    ]
