# Generated by Django 4.2.7 on 2024-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_userfit_alter_telegramuser_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfit',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
