# Generated by Django 4.2.7 on 2024-03-18 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_userfit_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userfit',
            name='fisrt_name',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.userfit', unique=True, verbose_name='Номер карты'),
        ),
        migrations.AddField(
            model_name='userfit',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='userfit',
            name='first_name',
            field=models.CharField(blank=True, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userfit',
            name='actived',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='userfit',
            name='created_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Коне абонемента'),
        ),
        migrations.AlterField(
            model_name='userfit',
            name='last_name',
            field=models.CharField(blank=True, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userfit',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
