# Generated by Django 4.2.7 on 2024-03-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_telegramuser_card_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfit',
            name='card',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Номер карты'),
        ),
    ]
