# Generated by Django 4.2.7 on 2024-04-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('date_at', models.DateField(verbose_name='Начало кации')),
                ('date_to', models.DateField(verbose_name='Конец акции')),
                ('promo', models.CharField(max_length=5, verbose_name='Промокод')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bot/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Акция фитнес-зала',
                'verbose_name_plural': 'Акции фитнес-зала',
            },
        ),
        migrations.CreateModel(
            name='MainTableAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время занятия')),
                ('number_of_recorded', models.PositiveSmallIntegerField(default=0, verbose_name='Количество записанных на занятие')),
                ('max_number_of_recorded', models.PositiveSmallIntegerField(default=10, verbose_name='Макс. органичение по записи')),
                ('check_canceled', models.BooleanField(default=False, verbose_name='Отменить занятие?')),
                ('check_canceled_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина отмены занятия')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.lessonfit', verbose_name='Занятие')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.trainerfit', verbose_name='Тренер')),
                ('week_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.datelessonfit', verbose_name='Недельное расписание')),
            ],
            options={
                'verbose_name': 'Основная информация',
                'verbose_name_plural': 'Основная информация',
            },
        ),
        migrations.CreateModel(
            name='UserFitLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_table_admin.maintableadmin', verbose_name='Занятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.userfit', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Клиент записанный на занятие',
                'verbose_name_plural': 'Клиенты записанные на занятия',
            },
        ),
    ]
