# Generated by Django 4.2.7 on 2024-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hallpromo',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AddField(
            model_name='maintableadmin',
            name='check_change_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина изменения занятия'),
        ),
        migrations.AlterField(
            model_name='hallpromo',
            name='date_at',
            field=models.DateField(verbose_name='Начало акции'),
        ),
    ]
