# Generated by Django 4.2.7 on 2024-03-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_delete_userfitlesson'),
        ('main_table_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFitLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.timelessonfit', verbose_name='Время занятия')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.lessonfit', verbose_name='Занятие')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.trainerfit', verbose_name='Тренер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.userfit', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Клиент записанный на занятие',
                'verbose_name_plural': 'Клиенты записанные на занятия',
            },
        ),
    ]
