# Generated by Django 4.2.7 on 2024-04-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table_admin', '0002_alter_hallpromo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfitlesson',
            name='is_come',
            field=models.BooleanField(default=False, verbose_name='Пришел/Не пришел.'),
        ),
    ]
