# Generated by Django 4.2.7 on 2024-03-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_table_admin', '0002_userfitlesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfitlesson',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userfitlesson',
            name='trainer',
        ),
        migrations.AlterField(
            model_name='maintableadmin',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время занятия'),
        ),
        migrations.AlterField(
            model_name='userfitlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_table_admin.maintableadmin', verbose_name='Занятие'),
        ),
    ]
