# Generated by Django 4.2.7 on 2024-04-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table_admin', '0002_userfitlesson_is_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallpromo',
            name='image',
            field=models.ImageField(null=True, upload_to='bot/', verbose_name='фото'),
        ),
    ]
