# Generated by Django 4.2.7 on 2024-03-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table_admin', '0003_remove_userfitlesson_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintableadmin',
            name='max_number_of_recorded',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Макс. органичение по записи'),
        ),
    ]
