# Generated by Django 4.2.7 on 2024-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table_admin', '0003_userfitlesson_is_come'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintableadmin',
            name='week_schedule',
        ),
        migrations.AlterField(
            model_name='userfitlesson',
            name='is_come',
            field=models.BooleanField(default=False, verbose_name='Пришел/Не пришел'),
        ),
    ]
